version: "3.1"
services:
    mysql:
        build:
            context: .
            dockerfile: mysql.DockerFile
        container_name: booked-database
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_USER: "root"
            MYSQL_ROOT_PASSWORD: "Hi"
            MYSQL_DATABASE: bookedscheduler
            MYSQL_USER: "booked_user"
            MYSQL_PASSWORD: "Hi"
            
        expose:
      # Opens port 3306 on the container
            - '3306'

    server:
        build: .
        image: booked-server:v1
        container_name: booked-server
        restart: always
        depends_on:
            - mysql
        links:
            - mysql:mysql
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html


