#!/usr/bin/bash
sudo sleep 1m
ID=$(sudo docker ps -aqf "name=booked-database")
IP=$(sudo docker inspect "$ID" --format='{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}')
sudo sed -i "99s/.*/\$conf['settings']['database']['hostspec'] = '$IP';"/ config/config.php
sudo sed -i "134s/.*/\$link = mysqli_connect('$IP', \$user="root", \$password="Hi");"/ lib/Application/Reservation/ReservationConflictIdentifier.php
sudo sed -i "137s/.*/\$link = mysqli_connect('$IP', \$user="root", \$password="Hi");"/ Pages/Ajax/ReservationDeletePage.php
