#!/usr/bin/bash
sudo sleep 1m
ID=$(sudo docker ps -aqf "name=booked-database")
IP=$(sudo docker inspect "$ID" --format='{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}')
sudo sed -i "99s/.*/\$conf['settings']['database']['hostspec'] = '$IP';"/ config/config.php
